document.writeln("<footer>");
document.writeln("			<div class=\'contain flex\'>");
document.writeln("				<div>");
document.writeln("					<h5>微信扫一扫 关注我们</h5>");
document.writeln("					<img src=\'images/index_44.png\'/>");
document.writeln("					<p>打开微信 <i class=\'fa fa-caret-right\'></i> 发现 <i class=\'fa fa-caret-right\'></i> 扫一扫 <i class=\'fa fa-caret-right\'></i> 关注</p>");
document.writeln("				</div>");
document.writeln("				<span class=\'fa fa-angle-right\'></span>");
document.writeln("				<div>");
document.writeln("					<h3>STEP 1</h3>");
document.writeln("					<p>关注过公众号后，进入公众号进行预约</p>");
document.writeln("					<p>通讯录 <i class=\'fa fa-caret-right\'></i> 公众号 <i class=\'fa fa-caret-right\'></i> 宜欧物流</p>");
document.writeln("				</div>");
document.writeln("				<span class=\'fa fa-angle-right\'></span>");
document.writeln("				<div>");
document.writeln("					<h3>STEP 2</h3>");
document.writeln("					<p>第一次关注的司机需要注册</p>");
document.writeln("					<p>我 <i class=\'fa fa-caret-right\'></i> 司机注册</p>");
document.writeln("				</div>");
document.writeln("				<span class=\'fa fa-angle-right\'></span>");
document.writeln("				<div>");
document.writeln("					<h3>STEP 3</h3>");
document.writeln("					<p>注册过的司机可以直接预约提货</p>");
document.writeln("					<p>我 <i class=\'fa fa-caret-right\'></i> 预约</p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</footer>");