document.writeln("<header>");
document.writeln("			<div class=\'contain flex\'>");
document.writeln("				<div class=\'flex logo\'>");
document.writeln("					<img src=\'images/index_03.png\' />");
document.writeln("					<div>");
document.writeln("						<h6>上海宜欧国际物流有限公司</h6>");
document.writeln("						<h6>OCEAN EAST International Logistics Co.Lbd.</h6>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'flex qr\'>");
document.writeln("					<h5>微信扫一扫<br />宜欧公众号</h5>");
document.writeln("					<img src=\'images/index_06.png\' />");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div class=\'head-nav med\'>");
document.writeln("				<nav class=\'contain\'>");
document.writeln("					<ul>");
document.writeln("						<li>");
document.writeln("							<p><a href=\'index.html\'>首页</a></p>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<p><a href=\'news.html\'>公司新闻</a></p>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<p><a href=\'javascript:void(0)\'>主营业务</a></p>");
document.writeln("							<div>");
document.writeln("								<a href=\'businessDetail.html\'>仓库物流</a>");
document.writeln("								<a href=\'businessDetail.html\'>保税物流</a>");
document.writeln("								<a href=\'businessDetail.html\'>运输服务</a>");
document.writeln("								<a href=\'businessDetail.html\'>堆场服务</a>");
document.writeln("								<a href=\'businessDetail.html\'>电商服务</a>");
document.writeln("							</div>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<p><a href=\'javascript:void(0)\'>特色服务</a></p>");
document.writeln("							<div>");
document.writeln("								<a href=\'\'>在线服务</a>");
document.writeln("								<a href=\'\'>逆向物流</a>");
document.writeln("								<a href=\'\'>CHB</a>");
document.writeln("							</div>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<p><a href=\'\'>业务查询</a></p>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<p><a href=\'joinUs.html\'>加入我们</a></p>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<p><a href=\'\'>关于我们</a></p>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<p><a href=\'contactUs.html\'>联系我们</a></p>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</nav>");
document.writeln("			</div>");
document.writeln("		</header>");